export const LoginConst = {
    USER_REGISTER : 'USER_REGISTER',
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGOUT : 'USER_LOGOUT'
}

export const ProductConst = {
    PRODUCT_CATEGORY_GET: 'PRODUCT_CATEGORY_GET',
    PRODUCT_SUBCATAGORY:'PRODUCT_SUBCATAGORY',
    PRODUCT_DETAILS:'PRODUCT_DETAILS',
}

export const CartConst = {
    CART_POST: 'CART_POST',
    CART_UPDATE: 'CART_UPDATE',
    CART_DELETE: 'CART_DELETE'
}